"""IMAP/SMTP email — direct, no filesystem inbox.

The agent sees `email_send(to, subject, body)` and `email_receive()` —
auto-generated by the base Interface from EmailMessage's dataclass fields.
"""

from __future__ import annotations

import asyncio
import email
import email.utils
import imaplib
import logging
import smtplib
from dataclasses import dataclass
from email import policy
from email.message import EmailMessage as StdEmailMessage
from typing import ClassVar, Optional

from pydantic import Field, SecretStr

from lib.interface import Interface, Message
from lib.settings import RootConfig
from lib.source import InputSettings

log = logging.getLogger(__name__)


class EmailSettings(InputSettings):
    KIND: ClassVar[str] = "interfaces"
    SECTION: ClassVar[str] = "email"
    REQUIRED_ENV: ClassVar[tuple[str, ...]] = ("EMAIL_PASSWORD",)
    username: str = ""
    imap_host: str = "imap.gmail.com"
    imap_port: int = 993
    smtp_host: str = "smtp.gmail.com"
    smtp_port: int = 587
    password: SecretStr | None = Field(
        default=None, validation_alias="EMAIL_PASSWORD"
    )
    allowed_senders: list[str] = Field(
        default_factory=list,
        json_schema_extra={
            "ui": "whitelist",
            "label": "Allowed senders",
            "placeholder": "alice@example.com",
            "help": "Email addresses permitted to wake the agent. Empty = no allowlist (every inbound email wakes).",
            "required_to_enable": False,
        },
    )

POLL_INTERVAL_S = 60
DRAIN_TIMEOUT_S = 300
ERROR_BACKOFF_S = 30


@dataclass
class EmailMessage(Message):
    subject: str = ""

    # Harness fields (omitted from the send-tool schema). `sender` is already
    # excluded by the base; nothing extra to hide here.
    TOOL_OMIT: ClassVar[tuple[str, ...]] = ()


class Email(Interface):
    name = "email"
    message_class = EmailMessage
    settings_cls = EmailSettings

    def __init__(self, agent_id: str, settings: RootConfig) -> None:
        super().__init__(agent_id, settings)
        cfg = EmailSettings(settings)
        self.imap_host = cfg.imap_host
        self.imap_port = cfg.imap_port
        self.smtp_host = cfg.smtp_host
        self.smtp_port = cfg.smtp_port
        self.username = cfg.username
        self.password = cfg.password.get_secret_value() if cfg.password else ""
        self.allowed_senders = [s.lower() for s in cfg.allowed_senders]
        self._drain = asyncio.Event()

    # --- lifecycle ---

    async def start(self, trigger_q) -> None:
        await super().start(trigger_q)
        asyncio.create_task(self._poll_loop(), name="email-poll")

    async def _poll_loop(self) -> None:
        """IMAP isn't latency-sensitive; poll every minute. On non-empty:
        signal, await drain, then sleep + re-check. IMAP IDLE would be the
        proper push fix but adds deps; out of scope."""
        while True:
            try:
                count = await asyncio.to_thread(self._check_unread)
            except Exception:
                log.exception("imap search failed")
                await asyncio.sleep(ERROR_BACKOFF_S)
                continue
            if count > 0:
                self._drain.clear()
                self._signal()
                try:
                    await asyncio.wait_for(
                        self._drain.wait(), timeout=DRAIN_TIMEOUT_S
                    )
                except asyncio.TimeoutError:
                    log.warning("email drain timeout; re-checking")
            await asyncio.sleep(POLL_INTERVAL_S)

    def _check_unread(self) -> int:
        with self._imap() as imap:
            return self._count_actionable_unread(imap)

    def _count_actionable_unread(self, imap: imaplib.IMAP4_SSL) -> int:
        """Count unread messages we'd actually act on.

        Without `allowed_senders`, every unread email is a wake. With it set,
        only unread mail from those addresses counts — newsletters and spam
        can't burn a no-op wake (which costs real money once the agent is
        Claude)."""
        if not self.allowed_senders:
            return len(self._search_ids(imap, "UNSEEN"))
        ids: set[bytes] = set()
        for sender in self.allowed_senders:
            ids.update(self._search_ids(imap, "UNSEEN", "FROM", f'"{sender}"'))
        return len(ids)

    # --- I/O ---

    async def receive(self) -> list[Message]:
        out: list[Message] = []
        try:
            with self._imap() as imap:
                for msg_id in self._search_ids(imap, "UNSEEN"):
                    parsed = self._fetch(imap, msg_id)
                    if parsed is None:
                        continue
                    sender = email.utils.parseaddr(parsed.get("From", ""))[1].lower()
                    if self.allowed_senders and sender not in self.allowed_senders:
                        log.info("ignoring email from non-allowed sender: %s", sender)
                        continue
                    out.append(
                        EmailMessage(
                            body=self._extract_body(parsed),
                            sender=sender,
                            to=self.username,
                            subject=parsed.get("Subject", "") or "",
                        )
                    )
        finally:
            self._drain.set()
        return out

    async def send(self, message: Message) -> str:
        if not message.to:
            raise RuntimeError("email send requires `to` to be set on the message")

        subject = getattr(message, "subject", "") or "(no subject)"

        mime = StdEmailMessage()
        mime["Subject"] = subject
        mime["From"] = self.username
        mime["To"] = message.to
        mime.set_content(message.body)

        with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
            server.starttls()
            server.login(self.username, self.password)
            server.send_message(mime)
        log.info("sent email to %s: %s", message.to, subject)
        return f"sent to {message.to}"

    # --- helpers ---

    def _imap(self) -> imaplib.IMAP4_SSL:
        imap = imaplib.IMAP4_SSL(self.imap_host, self.imap_port)
        imap.login(self.username, self.password)
        imap.select("INBOX")
        return imap

    @staticmethod
    def _search_ids(imap: imaplib.IMAP4_SSL, *criteria: str) -> list[bytes]:
        status, data = imap.search(None, *criteria)
        if status != "OK" or not data or data[0] is None:
            return []
        return data[0].split()

    @staticmethod
    def _fetch(imap: imaplib.IMAP4_SSL, msg_id: bytes) -> Optional[StdEmailMessage]:
        status, msg_data = imap.fetch(msg_id.decode(), "(RFC822)")
        if status != "OK" or not msg_data:
            return None
        first = msg_data[0]
        if not isinstance(first, tuple) or len(first) < 2:
            return None
        raw = first[1]
        if not isinstance(raw, (bytes, bytearray)):
            return None
        return email.message_from_bytes(bytes(raw), policy=policy.default)

    @staticmethod
    def _extract_body(parsed: StdEmailMessage) -> str:
        part = parsed.get_body(preferencelist=("plain",))
        if part is None:
            return ""
        content = part.get_content()
        return content if isinstance(content, str) else ""


Plugin = Email
