import email
import email.utils
import imaplib
import logging
import os
import smtplib
from dataclasses import dataclass
from email import policy
from email.message import EmailMessage as StdEmailMessage
from typing import ClassVar, Optional

from lib.interface import Interface, Message, Trigger

log = logging.getLogger("microagent.email")


@dataclass
class EmailMessage(Message):
    """Email payload — adds `subject` to the base body/to/sender fields."""

    subject: str = ""

    SCHEMA: ClassVar[dict[str, type]] = {"to": str, "subject": str, "body": str}


class Email(Interface):
    """IMAP/SMTP email — direct, no filesystem inbox.

    The agent sees `email_send(to, subject, body)` and `email_receive()` —
    auto-generated by the base Interface from EmailMessage.SCHEMA.
    """

    name = "email"
    message_class = EmailMessage

    def __init__(
        self,
        imap_host: str,
        smtp_host: str,
        username: str,
        imap_port: int = 993,
        smtp_port: int = 587,
        password_env: str = "EMAIL_PASSWORD",
        allowed_senders: Optional[list[str]] = None,
    ) -> None:
        self.imap_host = imap_host
        self.imap_port = imap_port
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = os.environ.get(password_env, "")
        self.allowed_senders = [s.lower() for s in (allowed_senders or [])]

    # --- lifecycle ---

    def trigger_wake(self) -> Optional[Trigger]:
        try:
            with self._imap() as imap:
                count = self._count_actionable_unread(imap)
        except Exception:
            log.exception("trigger_wake: imap search failed")
            return None
        if count == 0:
            return None
        return Trigger(interface=self)

    def _count_actionable_unread(self, imap: imaplib.IMAP4_SSL) -> int:
        """Count unread messages we'd actually act on.

        Without `allowed_senders`, every unread email is a wake. With it set,
        only unread mail from those addresses counts — so newsletters, account
        notices, and spam can't burn a no-op wake (which costs real money once
        the agent is Claude).
        """
        if not self.allowed_senders:
            return len(self._search_ids(imap, "UNSEEN"))

        ids: set[bytes] = set()
        for sender in self.allowed_senders:
            ids.update(self._search_ids(imap, "UNSEEN", "FROM", f'"{sender}"'))
        return len(ids)

    # --- I/O ---

    async def receive(self) -> list[Message]:
        out: list[Message] = []
        with self._imap() as imap:
            for msg_id in self._search_ids(imap, "UNSEEN"):
                parsed = self._fetch(imap, msg_id)
                if parsed is None:
                    continue
                sender = email.utils.parseaddr(parsed.get("From", ""))[1].lower()
                if self.allowed_senders and sender not in self.allowed_senders:
                    log.info("ignoring email from non-allowed sender: %s", sender)
                    continue
                out.append(
                    EmailMessage(
                        body=self._extract_body(parsed),
                        sender=sender,
                        to=self.username,
                        subject=parsed.get("Subject", "") or "",
                    )
                )
        return out

    async def send(self, message: Message) -> str:
        if not message.to:
            raise RuntimeError("email send requires `to` to be set on the message")

        subject = getattr(message, "subject", "") or "(no subject)"

        mime = StdEmailMessage()
        mime["Subject"] = subject
        mime["From"] = self.username
        mime["To"] = message.to
        mime.set_content(message.body)

        with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
            server.starttls()
            server.login(self.username, self.password)
            server.send_message(mime)
        log.info("sent email to %s: %s", message.to, subject)
        return f"sent to {message.to}"

    # --- helpers ---

    def _imap(self) -> imaplib.IMAP4_SSL:
        imap = imaplib.IMAP4_SSL(self.imap_host, self.imap_port)
        imap.login(self.username, self.password)
        imap.select("INBOX")
        return imap

    @staticmethod
    def _search_ids(imap: imaplib.IMAP4_SSL, *criteria: str) -> list[bytes]:
        status, data = imap.search(None, *criteria)
        if status != "OK" or not data or data[0] is None:
            return []
        return data[0].split()

    @staticmethod
    def _fetch(imap: imaplib.IMAP4_SSL, msg_id: bytes) -> Optional[StdEmailMessage]:
        status, msg_data = imap.fetch(msg_id.decode(), "(RFC822)")
        if status != "OK" or not msg_data:
            return None
        first = msg_data[0]
        if not isinstance(first, tuple) or len(first) < 2:
            return None
        raw = first[1]
        if not isinstance(raw, (bytes, bytearray)):
            return None
        # policy.default gives us a modern EmailMessage with get_body() etc.
        return email.message_from_bytes(bytes(raw), policy=policy.default)

    @staticmethod
    def _extract_body(parsed: StdEmailMessage) -> str:
        part = parsed.get_body(preferencelist=("plain",))
        if part is None:
            return ""
        content = part.get_content()
        return content if isinstance(content, str) else ""
